//==========================================================================================================================
//Key is used to ensure the consistency of file version and content, and cannot be modified.
//Version Control is the version number written when the file is generated and cannot be modified.
//ToolMessage is used to record related information of any tool that has processed the file and cannot be manually modified.
//UserMessage is used by the user to write any information, which can be modified in any way.
//Content is the actual payload of the file.
//Parameter is the additional parameter information carried by the file and cannot be modified in any way.

//Key is generated by the hash of Version Control, Content and Parameter to ensure the consistency of the file.
//These three parts do not allow any individual modification
//==========================================================================================================================


//[UHDL]Key Start [md5:f726b0dd8414ccd57a6812621b9aef18]
//Version Control Hash: 3accddf64b1dd03abeb9b0b3e5a7ba44
//Content Hash: e016d916db2f85cfa7a4ddbac02fc89d
//Parameter Hash: d41d8cd98f00b204e9800998ecf8427e
//[UHDL]Key End [md5:f726b0dd8414ccd57a6812621b9aef18]

//[UHDL]Version Control Start [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]
//[UHDL]Version Control Version:1.0.1
//[UHDL]Version Control End [md5:3accddf64b1dd03abeb9b0b3e5a7ba44]

//[UHDL]Tool Message Start [md5:6b9fa9ef5788ecfaf06527b57cc3cb10]
//Written by UHDL in 2022-11-15 12:59:10
//[UHDL]Tool Message End [md5:6b9fa9ef5788ecfaf06527b57cc3cb10]

//[UHDL]User Message Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]User Message End [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Content Start [md5:e016d916db2f85cfa7a4ddbac02fc89d]
module FirstComp_ (
	input        clk  ,
	input        rst_n,
	input        din1 ,
	input        din2 ,
	output [1:0] dout );
	reg [1:0] dout_reg;
	assign dout = dout_reg;
	
	always @(posedge clk or negedge rst_n) begin
	    if(~rst_n) dout_reg <= 2'b0;
	    else dout_reg <= (din1 + din2);
	end
	

endmodule
//[UHDL]Content End [md5:e016d916db2f85cfa7a4ddbac02fc89d]

//[UHDL]Parameter Start [md5:d41d8cd98f00b204e9800998ecf8427e]

//[UHDL]Parameter End [md5:d41d8cd98f00b204e9800998ecf8427e]

