import os
import sys
import subprocess
import tempfile
import yaml
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# Import VComponent for TemplateComponent inheritance
from .VComponent import VComponent


def _ensure_cli_available(cmd: str = "ip_builder") -> bool:
    """Best-effort probe for ip_builder CLI on PATH. Returns True if invocable."""
    try:
        subprocess.run([cmd, "--help"], check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        return True
    except FileNotFoundError:
        return False


class TemplateComponent(VComponent):
    """
    TemplateComponent extends VComponent to wrap RTL generated by TemplateIP.
    
    It takes a TemplateIPConfig and top module name, automatically handles the
    build process, and creates a VComponent instance using the generated unity wrapper.
    
    Usage:
        cfg = TemplateIPConfig(
            name="my_ip",
            filelist="path/to/filelist.f",
            prefix="NPU_",
        )
        comp = TemplateComponent(config=cfg, top="my_top_module")
    """
    
    def __init__(self, config: 'TemplateIPConfig', top: str, instance: Optional[str] = None, **kwargs) -> None:
        """
        Create a TemplateComponent from a TemplateIPConfig and top module name.
        
        Args:
            config: TemplateIPConfig object containing IP configuration
            top: Top module name to instantiate
            instance: Instance name for AST generation (defaults to top if not provided)
            **kwargs: Additional parameters passed to VComponent (e.g., slang options, RTL parameters)
        """
        # Get or create TemplateIP from config
        self._parent_template = config.get_or_create_ip()
        
        # Execute temp_build to generate RTL with unity wrapper
        self._parent_template.temp_build()
        
        # Get unity wrapper path
        unity_wrapper_path = self._parent_template.get_unity_wrapper()
        
        # Initialize VComponent with unity wrapper file and top module
        if instance is None:
            instance = top
        
        # Prepend prefix to top module name (ip_builder adds prefix to module names)
        prefixed_top = config.prefix + top
        
        super().__init__(
            file=unity_wrapper_path,
            top=prefixed_top,
            instance=instance,
            **kwargs
        )
    
    @property
    def parent_template(self) -> 'TemplateIP':
        """Get the parent TemplateIP that generated this component."""
        return self._parent_template
    
    def _create_this_vfile(self, path):
        """
        Override _create_this_vfile to trigger TemplateIP release build.
        
        This method is called by Component.generate_verilog() -> _create_all_vfile() chain.
        It triggers the parent TemplateIP to build the RTL files in the release directory.
        
        Args:
            path: The base output directory from component hierarchy (ignored for TemplateIP)
        """
        # Build using TemplateIP's release_output_dir
        self._parent_template.release_build()
    
    def _generate_filelist_core(self, prefix=''):
        """
        Override filelist generation for TemplateComponent.
        
        TemplateComponent represents RTL generated by TemplateIP (via ip_builder).
        Instead of generating .v files in the wrapper's output directory,
        we reference the TemplateIP's release filelist using the -f directive.
        
        Args:
            prefix: Path prefix for generated files (unused for TemplateIP)
        
        Returns:
            List containing the -f directive for this TemplateIP's release filelist
        """
        name_list = []
        template_ip = self.parent_template
        
        # Use env_var prefix if available, otherwise absolute path
        if template_ip.env_var:
            # Use environment variable prefix (e.g., $NPU_DTI/npu_dti_filelist.f)
            filelist_path = f"${template_ip.env_var}/{template_ip.prefix}filelist.f"
        else:
            # Fallback to absolute path from release directory
            filelist_path = os.path.join(
                template_ip.release_output_dir,
                f"{template_ip.prefix}filelist.f"
            )
        
        name_list.append(f"-f {filelist_path}")
        
        return name_list


@dataclass
class TemplateIPConfig:
    """
    TemplateIPConfig captures all parameters required to instantiate a TemplateIP.

    Fields mirror TemplateIP.__init__ and are intentionally limited to construction-time
    options (build-time options like output_dir are intentionally excluded and should
    be provided to TemplateIP.build()).

    The config supports programmatic macro configuration via set_macro(), which
    internally manages a dictionary that gets serialized to a temporary YAML file
    when instantiating the TemplateIP.

    Usage:
        cfg = TemplateIPConfig(
            name="axi_lite",
            filelist="path/to/filelist.f",
            prefix="NPU_",
            env_var="AXI_LITE_DIR",
        )
        
        # Configure macros programmatically
        cfg.set_macro("DATA_WIDTH", 32)
        cfg.set_macro("ADDR_WIDTH", 16)

        # Create a new TemplateIP (or return existing singleton if already created)
        ip = cfg.get_or_create_ip()
    """

    # Required
    name: str
    prefix: str

    # One of the two must be provided
    src_dir: Optional[str] = None
    filelist: Optional[str] = None

    # Optional flags/paths
    keep_prefix: bool = False
    macro_yaml: Optional[str] = None
    env_var: Optional[str] = None
    release_output_dir: Optional[str] = None
    
    # Internal macro storage - not part of constructor signature
    _macros: Dict[str, Any] = field(default_factory=dict, init=False, repr=False)
    _generated_macro_yaml: Optional[str] = field(default=None, init=False, repr=False)

    def set_macro(self, key: str, value: Any) -> None:
        """
        Set a macro definition for this TemplateIP configuration.
        
        Macros are stored internally and will be written to a temporary YAML file
        when instantiating the TemplateIP. This allows programmatic configuration
        without requiring a pre-existing macro_yaml file.
        
        Args:
            key: Macro name (e.g., "DATA_WIDTH")
            value: Macro value (e.g., 32, "hello", etc.)
        
        Example:
            cfg = TemplateIPConfig(name="my_ip", filelist="...", prefix="PRE_")
            cfg.set_macro("WIDTH", 32)
            cfg.set_macro("DEPTH", 1024)
        """
        self._macros[key] = value
        # Invalidate any previously generated YAML
        self._generated_macro_yaml = None
    
    def _ensure_macro_yaml(self) -> Optional[str]:
        """
        Generate a temporary YAML file from configured macros if needed.
        
        Returns:
            Path to the macro YAML file (either user-provided or generated),
            or None if no macros are configured and no macro_yaml was provided.
        """
        # If user provided an explicit macro_yaml file, use it (takes precedence)
        if self.macro_yaml:
            return self.macro_yaml
        
        # If no macros configured, no need for YAML
        if not self._macros:
            return None
        
        # If we've already generated a YAML for current macros, reuse it
        if self._generated_macro_yaml and os.path.exists(self._generated_macro_yaml):
            return self._generated_macro_yaml
        
        # Generate a new temporary YAML file
        with tempfile.NamedTemporaryFile(
            mode='w',
            suffix='.yaml',
            prefix=f'{self.name}_macros_',
            delete=False,
            encoding='utf-8'
        ) as f:
            yaml.dump(self._macros, f, default_flow_style=False)
            self._generated_macro_yaml = f.name
        
        return self._generated_macro_yaml

    def validate(self) -> None:
        """Validate config consistency: exactly one of src_dir/filelist, and requireds."""
        if not self.name:
            raise ValueError("TemplateIPConfig.name is required")
        if self.prefix is None:
            raise ValueError("TemplateIPConfig.prefix is required")
        if (self.src_dir is None) == (self.filelist is None):
            # Either both None or both provided -> invalid
            raise ValueError("Exactly one of src_dir or filelist must be provided")

    def get_or_create_ip(self) -> 'TemplateIP':
        """
        Get or create a TemplateIP via the global TemplateManager singleton.
        
        If a TemplateIP with this name already exists, returns it.
        Otherwise, creates a new TemplateIP with this configuration.
        
        Returns:
            TemplateIP instance (singleton by name)
        """
        self.validate()
        return TemplateManager().get_or_create(self)

    def __del__(self) -> None:
        """Clean up temporary macro YAML file if generated."""
        if self._generated_macro_yaml and os.path.exists(self._generated_macro_yaml):
            try:
                os.unlink(self._generated_macro_yaml)
            except Exception:
                pass  # Best effort cleanup


class TemplateIP:
    """
    TemplateIP wraps an ip_builder task (prefixing + filelist generation) and
    provides methods to build RTL bundles and create VComponents.

    TemplateIP instances are managed by TemplateManager to ensure singleton behavior per name.
    Do not instantiate TemplateIP directly - use TemplateIPConfig.get_or_create_ip() instead.

    Typical usage:
        # Create configuration
        cfg = TemplateIPConfig(
            name="axi_lite",
            filelist="path/to/src/filelist.f",
            prefix="NPU_",
            env_var="AXI_LITE_DIR",
        )
        
        # Get or create TemplateIP via manager (ensures singleton)
        ip = cfg.get_or_create_ip()
        
        # Build for temporary usage (unity wrapper + filelist)
        ip.temp_build()
        
        # Build for release
        ip.release_build()
        
    Note:
        Both temp_build() and release_build() are executed only once during 
        the lifetime of the TemplateIP instance.
    """

    def __init__(
        self,
        name: str,
        *,
        src_dir: Optional[str] = None,
        filelist: Optional[str] = None,
        prefix: str,
        keep_prefix: bool = False,
        macro_yaml: Optional[str] = None,
        env_var: Optional[str] = None,
        release_output_dir: Optional[str] = None,
    ) -> None:
        """
        Initialize a TemplateIP instance.
        
        Note: This should typically not be called directly. Use TemplateIPConfig.get_or_create_ip()
        or TemplateManager.get_or_create() to ensure singleton behavior.
        """
        # Validate parameters
        if not src_dir and not filelist:
            raise ValueError("Either src_dir or filelist must be provided")
        if src_dir and filelist:
            raise ValueError("Provide only one of src_dir or filelist")

        self.name = name
        self.src_dir = os.path.abspath(src_dir) if src_dir else None
        self.filelist = os.path.abspath(filelist) if filelist else None
        self.prefix = prefix
        self.keep_prefix = keep_prefix
        self.macro_yaml = os.path.abspath(macro_yaml) if macro_yaml else None
        self.env_var = env_var  # environment variable name for filelist path entries

        # Output directories
        self._temp_output_dir = os.path.join(os.getcwd(), "build", "temp", self.name)
        self._release_output_dir = release_output_dir
        if self._release_output_dir:
            self._release_output_dir = os.path.abspath(self._release_output_dir)
        else:
            self._release_output_dir = os.path.join(os.getcwd(), "build", "release", self.name)
        
        # Build state tracking - both builds only execute once in lifecycle
        self._temp_build_completed: bool = False
        self._release_build_completed: bool = False

        # CLI name (can be overridden for testing via env)
        self._ipb_cmd = os.environ.get("IP_BUILDER_CLI", "ip_builder")
    
    @property
    def temp_output_dir(self) -> str:
        """Get the temp output directory."""
        return self._temp_output_dir
    
    @property
    def release_output_dir(self) -> str:
        """Get the release output directory."""
        return self._release_output_dir

    def _build(
        self,
        output_dir: str,
        exclude_foundation_ip: bool = False,
    ) -> str:
        """Internal method to run ip_builder and generate RTL in specified output_dir.

        Args:
            output_dir: Output directory for build artifacts
            exclude_foundation_ip: Whether to exclude foundation IP files when building

        Returns:
            The path to the generated filelist.
        """
        # Ensure output directory is absolute
        output_dir = os.path.abspath(output_dir)
        os.makedirs(output_dir, exist_ok=True)
        
        # Generate filelist path
        generated_filelist = os.path.join(output_dir, f"{self.prefix}filelist.f")
        
        # Always build when called (no automatic freshness checking)
        if self.src_dir:
            # 1) run ip_builder in src-folder mode
            args = ["-s", self.src_dir, "-p", self.prefix, "-d", output_dir]
            if self.keep_prefix:
                args.append("-k")
            if self.env_var:
                args += ["-e", self.env_var]
            self._run_ip_builder(args)
            # 2) generate a filelist that indexes all generated SV/V files
            rel_files: List[str] = []
            for root, _dirs, files in os.walk(output_dir):
                for fn in files:
                    if fn.endswith((".sv", ".v")):
                        abspath = os.path.join(root, fn)
                        rel = os.path.relpath(abspath, output_dir)
                        rel_files.append(rel)
            rel_files.sort()
            with open(generated_filelist, "w", encoding="utf-8") as f:
                for rel in rel_files:
                    if self.env_var:
                        f.write(f"${self.env_var}/{rel}\n")
                    else:
                        f.write(rel + "\n")
        else:
            # filelist mode: ip_builder handles expansion and filelist emission
            args = ["-f", self.filelist, "-p", self.prefix, "-d", output_dir]
            if self.keep_prefix:
                args.append("-k")
            if not exclude_foundation_ip:
                args.append("-ne")
            if self.macro_yaml:
                args += ["-m", self.macro_yaml]
            if self.env_var:
                args += ["-e", self.env_var]
            self._run_ip_builder(args)
        
        return generated_filelist
    
    def temp_build(self) -> str:
        """
        Build in temp directory with unity wrapper and filelist.
        
        This method is executed only once during the lifetime of the TemplateIP instance.
        Subsequent calls will skip the build and return the existing filelist path.
        
        Returns:
            Path to the generated filelist in temp directory
        """
        if self._temp_build_completed:
            # Already built, return existing filelist
            return os.path.join(self._temp_output_dir, f"{self.prefix}filelist.f")
        
        # Perform the build
        filelist_path = self._build(
            output_dir=self._temp_output_dir,
            exclude_foundation_ip=False,  # Include all dependencies
        )
        
        # Generate expanded filelist and unity wrapper for temp build
        self._write_expanded_filelist(self._temp_output_dir, filelist_path)
        self._write_unity_wrapper(self._temp_output_dir, filelist_path)
        
        # Mark as completed
        self._temp_build_completed = True
        
        return filelist_path
    
    def release_build(self) -> str:
        """
        Build in release directory.
        
        This method is executed only once during the lifetime of the TemplateIP instance.
        Subsequent calls will skip the build and return the existing filelist path.
        
        Returns:
            Path to the generated filelist in release directory
        """
        if self._release_build_completed:
            # Already built, return existing filelist
            return os.path.join(self._release_output_dir, f"{self.prefix}filelist.f")
        
        # Perform the build
        filelist_path = self._build(
            output_dir=self._release_output_dir,
            exclude_foundation_ip=True,   # Exclude foundation IP
        )
        
        # Mark as completed
        self._release_build_completed = True
        
        return filelist_path
    
    def get_unity_wrapper(self) -> str:
        """
        Get the path to the temp unity wrapper file.
        
        If temp_build has not been called yet, it will be called automatically.
        
        Returns:
            Path to the unity wrapper file in temp directory
        """
        if not self._temp_build_completed:
            self.temp_build()
        
        return os.path.join(self._temp_output_dir, f"{self.prefix}unity_wrapper.sv")

    def _write_expanded_filelist(self, output_dir: str, generated_filelist: str) -> str:
        """Create a filelist with any leading $ENV/ prefixes replaced by absolute paths.

        Many SystemVerilog tools don't expand $ENV variables inside .f files. Since
        ip_builder emits lines like "$ENV/path/to/file.sv", we produce a sibling
        filelist where these are rewritten to absolute paths under output_dir.
        Returns the path to the expanded filelist.
        """
        src_fl = generated_filelist
        base = os.path.splitext(generated_filelist)[0]
        dst_fl = base + ".expanded.f"
        try:
            with open(src_fl, "r", encoding="utf-8") as fin, open(dst_fl, "w", encoding="utf-8") as fout:
                for raw in fin:
                    line = raw.strip()
                    if not line or line.startswith("#"):
                        continue
                    # Replace a leading $ENV/ prefix with output_dir joined path
                    if self.env_var and line.startswith(f"${self.env_var}/"):
                        rel = line[len(self.env_var) + 2 :]  # skip $ENV/
                        abspath = os.path.join(output_dir, rel)
                        fout.write(abspath + "\n")
                    elif line.startswith("$") and "/" in line:
                        # Generic $FOO/rel/path -> assume this bundle's output_dir
                        rel = line.split("/", 1)[1]
                        abspath = os.path.join(output_dir, rel)
                        fout.write(abspath + "\n")
                    else:
                        # Relative path from output_dir -> make absolute for robustness
                        if not os.path.isabs(line):
                            line = os.path.join(output_dir, line)
                        fout.write(line + "\n")
        except FileNotFoundError:
            # If original filelist missing, cannot expand
            raise RuntimeError(
                f"Generated filelist not found: {src_fl}. "
                "Please ensure _build() has been called successfully."
            )
        return dst_fl

    def _write_unity_wrapper(self, output_dir: str, generated_filelist: str) -> str:
        """Create a single SystemVerilog wrapper that `include`s all generated files.

        The wrapper ensures all files are compiled as one compilation unit without
        requiring a compiler flag. The macro file (if present) is included first.
        Returns the path to the wrapper file.
        
        Note: This method should only be called after _build() has completed.
        """
        # Get list of generated files from expanded filelist
        base = os.path.splitext(generated_filelist)[0]
        fl = base + ".expanded.f"
        if not os.path.exists(fl):
            raise RuntimeError(
                f"Expanded filelist not found: {fl}. "
                "This method should only be called after _build() completes."
            )
        
        files: List[str] = []
        try:
            with open(fl, "r", encoding="utf-8") as f:
                for line in f:
                    p = line.strip()
                    if not p or p.startswith("#"):
                        continue
                    if not os.path.isabs(p):
                        p = os.path.join(output_dir, p)
                    files.append(p)
        except Exception:
            pass
        
        if not files:
            raise RuntimeError("No generated files to include in unity wrapper")

        # Sort with macro file first if found
        macro_first: List[str] = []
        others: List[str] = []
        for p in files:
            base = os.path.basename(p)
            if base.endswith("_macros.sv") or base.endswith("macros.sv"):
                macro_first.append(p)
            else:
                others.append(p)
        ordered = macro_first + others

        wrapper_path = os.path.join(output_dir, f"{self.prefix}unity_wrapper.sv")
        with open(wrapper_path, "w", encoding="utf-8") as f:
            f.write("// Auto-generated by TemplateIP: unity wrapper to include all generated files\n")
            f.write("// DO NOT EDIT\n\n")
            # Prefer relative includes from output_dir so tools can resolve via --include-directory
            for p in ordered:
                try:
                    rel = os.path.relpath(p, output_dir)
                except Exception:
                    rel = p
                # Fallback to absolute if file escapes output_dir
                if rel.startswith(".."):
                    rel = p
                f.write(f"`include \"{rel}\"\n")
        return wrapper_path

    def _run_ip_builder(self, args: List[str]) -> None:
        """Run ip_builder via CLI, with fallback to repo-local script if needed."""
        # Try CLI first if present
        cli_ok = _ensure_cli_available(self._ipb_cmd)
        if cli_ok:
            try:
                subprocess.run([self._ipb_cmd] + args, check=True)
                return
            except subprocess.CalledProcessError as e:
                # proceed to fallback
                pass
        # Fallback: locate local ip_builder/ip_builder.py
        script = self._find_local_ip_builder()
        if not script:
            # If CLI existed but failed, re-raise; else give clear error
            if cli_ok:
                raise
            raise RuntimeError("Cannot locate ip_builder CLI or local script to run.")
        subprocess.run([sys.executable, script] + args, check=True)

    def _find_local_ip_builder(self) -> Optional[str]:
        """Search upwards for a repo-local ip_builder/ip_builder.py script."""
        here = os.path.dirname(os.path.abspath(__file__))
        for up in range(1, 8):
            root = os.path.abspath(os.path.join(here, *([".."] * up)))
            candidate = os.path.join(root, "ip_builder", "ip_builder.py")
            if os.path.isfile(candidate):
                return candidate
        # Also check CWD
        candidate = os.path.join(os.getcwd(), "ip_builder", "ip_builder.py")
        if os.path.isfile(candidate):
            return candidate
        return None

   
class TemplateManager:
    """
    TemplateManager manages all TemplateIP instances as singletons by name.
    
    TemplateManager itself is a global singleton - only one instance can exist.
    Attempting to create multiple instances will return the same singleton.
    
    Each TemplateIP is uniquely identified by its name. When requesting a
    TemplateIP with the same name, the manager returns the existing instance
    instead of creating a new one.
    
    Usage via TemplateIPConfig (recommended):
        cfg = TemplateIPConfig(name="axi_lite", filelist="...", prefix="NPU_")
        ip = cfg.get_or_create_ip()  # Uses global singleton manager
        
    Direct usage:
        manager = TemplateManager()  # Always returns same singleton
        ip = manager.get_or_create(cfg)
    """
    
    _instance: Optional['TemplateManager'] = None
    _registry: Dict[str, TemplateIP] = {}
    
    def __new__(cls) -> 'TemplateManager':
        """Ensure only one TemplateManager instance exists (singleton pattern)."""
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance
    
    def get_or_create(self, config: TemplateIPConfig) -> TemplateIP:
        """
        Get existing TemplateIP by name, or create a new one using the provided config.
        
        Args:
            config: TemplateIPConfig containing all parameters for the TemplateIP
        
        Returns:
            TemplateIP instance associated with the config's name (singleton)
        
        Note:
            If a TemplateIP with the same name already exists, returns the existing
            instance without modifying it. To update, call unregister() first.
        """
        # Check if already exists (use class-level registry)
        if config.name in TemplateManager._registry:
            return TemplateManager._registry[config.name]
        
        # Validate config
        config.validate()
        
        # Ensure macro_yaml is set (either user-provided or generated from _macros)
        effective_macro_yaml = config._ensure_macro_yaml()
        
        # Create new TemplateIP instance
        ip = TemplateIP(
            name=config.name,
            src_dir=config.src_dir,
            filelist=config.filelist,
            prefix=config.prefix,
            keep_prefix=config.keep_prefix,
            macro_yaml=effective_macro_yaml,
            env_var=config.env_var,
            release_output_dir=config.release_output_dir,
        )
        
        TemplateManager._registry[config.name] = ip
        return ip
    
    def get(self, name: str) -> Optional[TemplateIP]:
        """
        Get an existing TemplateIP by name without creating it.
        
        Args:
            name: Name of the TemplateIP to retrieve
        
        Returns:
            TemplateIP instance if found, None otherwise
        """
        return TemplateManager._registry.get(name)
    
    def has(self, name: str) -> bool:
        """Check if a TemplateIP with the given name exists in this manager."""
        return name in TemplateManager._registry
    
    def unregister(self, name: str) -> bool:
        """
        Remove a TemplateIP from the registry.
        
        Args:
            name: Name of the TemplateIP to remove
        
        Returns:
            True if the TemplateIP was removed, False if it didn't exist
        """
        if name in TemplateManager._registry:
            del TemplateManager._registry[name]
            return True
        return False
    
    def clear(self) -> None:
        """Remove all TemplateIP instances from the registry."""
        TemplateManager._registry.clear()
    
    def list_names(self) -> List[str]:
        """Get a list of all registered TemplateIP names."""
        return list(TemplateManager._registry.keys())

